sudo: false
language: go
go:
  - 1.5
  - tip
os:
  - linux
  - osx
git:
  submodules: false
matrix:
  allow_failures:
    - go: tip
script:
  - make testnodb
install:
  - go get github.com/stretchr/testify
  - go get -d -v ./...
